/**
 * Local message factories mirroring `@deepseek-ai/dsh-llm` (deep-frozen,
 * detached identities). The surface ships no llm runtime import, so these
 * stay byte-compatible with the loop's contract instead.
 *
 * @module dsh-terminal/core/messages
 */

import { randomUUID } from 'node:crypto'

/** Recursively freeze a plain value (mirrors dsh-llm's deepFreeze). */
function deepFreeze<T>(value: T): T {
  if (typeof value !== 'object' || value === null || Object.isFrozen(value)) return value
  const record = value as Record<string | symbol, unknown>
  for (const key of Reflect.ownKeys(record)) deepFreeze(record[key])
  return Object.freeze(value)
}

/** User-role message input (role/id are minted here). */
export interface UserMessageInput {
  content: { type: string; text?: string }[]
  source: { kind: string; plugin?: string; form?: string; summary?: string }
}

/**
 * Create one identified, immutable user-role message.
 * @param input - content blocks and producer source.
 * @returns the frozen message the inbox accepts.
 */
export function createUserMessage(input: UserMessageInput): unknown {
  return deepFreeze(structuredClone({
    id: randomUUID(),
    role: 'user',
    ...input,
  }))
}

/** Bound for a notice summary (mirrors dsh-llm's 120-char bound). */
const NOTICE_SUMMARY_MAX_CHARS = 120

function boundSummary(summary: string): string {
  return summary.length <= NOTICE_SUMMARY_MAX_CHARS
    ? summary
    : `${summary.slice(0, NOTICE_SUMMARY_MAX_CHARS - 1)}…`
}

/**
 * Create the durable model-switch notice upstream model-selection appends.
 * @param from - previous `provider/model` label.
 * @param to - selected `provider/model` label.
 * @returns the frozen notice message.
 */
export function createModelSwitchNotice(from: string, to: string): unknown {
  return createUserMessage({
    content: [{
      type: 'text',
      text: `[model changed: assistant turns above this point were generated by ${from}; the session continues with ${to}]`,
    }],
    source: {
      kind: 'plugin',
      plugin: 'dsh-terminal',
      form: 'notice',
      summary: boundSummary(`${from} → ${to}`),
    },
  })
}
